plugins {
	id 'java'
	id 'application'
	id 'org.springframework.boot' version '3.3.3'
	id 'io.spring.dependency-management' version '1.1.6'



}

group = 'com.moyeobwayo'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

ext {
	set('springBootAdminVersion', "3.4.1")
}
repositories {
	mavenCentral()
}

dependencies {
	//스웨거 의존성
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.postgresql:postgresql:42.7.3'
	implementation 'org.apache.httpcomponents:httpclient:4.5.13'
	implementation 'org.apache.httpcomponents:httpcore:4.4.13'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.json:json:20210307'
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'  // 최신 버전
	implementation 'com.fasterxml.jackson.core:jackson-annotations:2.15.2'  // 최신 버전
	implementation 'com.fasterxml.jackson.core:jackson-core:2.15.2'  // 최신 버전
	implementation 'org.springframework.boot:spring-boot-configuration-processor:2.7.4'
	implementation group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1.1'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.postgresql:postgresql:42.7.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'com.jayway.jsonpath:json-path'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	//JSON 도구

	// jwt 의존성 추가
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	implementation 'de.codecentric:spring-boot-admin-starter-client:3.3.3'

	implementation 'org.springframework.boot:spring-boot-starter-actuator'}

dependencyManagement {
	imports {
		mavenBom "de.codecentric:spring-boot-admin-dependencies:${springBootAdminVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
